// Writes src/components/common/iconGlyphs.ts: the path data of the Phosphor
// icons the site uses, in the one or two weights it draws them in.
//
// Each Phosphor icon module carries all six weights (regular, thin, light,
// bold, fill, duotone), so importing the icons shipped six times the path data
// the site needs. This copies only the weights in use, straight from
// Phosphor's own definitions, so the glyphs stay exactly Phosphor's.
//
// Run after adding an icon or changing a weight: npm run icons
import { writeFileSync } from 'node:fs';

// The site's name for each icon, and the Phosphor icon drawn for it.
const ICONS = {
  github: 'GithubLogo',
  linkedin: 'LinkedinLogo',
  facebook: 'FacebookLogo',
  discord: 'DiscordLogo',
  mail: 'EnvelopeSimple',
  phone: 'Phone',
  download: 'DownloadSimple',
  external: 'ArrowSquareOut',
  sun: 'Sun',
  moon: 'Moon',
  menu: 'List',
  close: 'X',
  star: 'Star',
  arrow: 'ArrowRight',
  chevron: 'CaretDown',
  check: 'Check',
  alert: 'WarningCircle',
  user: 'User',
  tag: 'Tag',
  message: 'Chat',
  copy: 'Copy',
  arrowUp: 'ArrowUp',
  arrowLeft: 'ArrowLeft',
  pause: 'Pause',
  play: 'Play',
};

// Everything is drawn in the regular weight; a chosen star is solid.
const FILLED = new Set(['star']);

// The package does not export its definitions, so they are read from disk.
const defs = new URL('../node_modules/@phosphor-icons/react/dist/defs/', import.meta.url);

/** The `d` of every path in one weight of one icon, in drawing order. */
function paths(weights, weight) {
  const element = weights.get(weight);
  if (!element) throw new Error(`No ${weight} weight`);
  const children = [element.props.children].flat();
  return children.map((child) => {
    if (child.type !== 'path' || Object.keys(child.props).some((key) => key !== 'd')) {
      throw new Error(`Unexpected ${child.type} in the ${weight} weight`);
    }
    return child.props.d;
  });
}

const entries = [];
for (const [name, phosphor] of Object.entries(ICONS)) {
  const { default: weights } = await import(new URL(`${phosphor}.es.js`, defs).href);
  const glyph = { regular: paths(weights, 'regular') };
  if (FILLED.has(name)) glyph.fill = paths(weights, 'fill');
  entries.push(`  ${name}: ${JSON.stringify(glyph)},`);
}

const source = `// Generated by scripts/icons.mjs from @phosphor-icons/react. Do not edit by
// hand: change the list in the script and run \`npm run icons\`.
// Phosphor Icons, MIT License, https://phosphoricons.com

export const glyphs = {
${entries.join('\n')}
} as const satisfies Record<string, { regular: readonly string[]; fill?: readonly string[] }>;
`;

writeFileSync(new URL('../src/components/common/iconGlyphs.ts', import.meta.url), source);
console.log(`Wrote ${entries.length} icons.`);
